name: Versioning

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.3
        with:
          current-version: '2.11.7-alpha3'
          version-fragment: 'feature'

      - name: Do something with your bumped release version
        run: echo ${{ steps.bump_version.outputs.next-version }}

      - name: Write version to file
        uses: jaywcjlove/github-action-modify-file-content@v2.0.3
        with:
          path: "version.txt"
          body: "app version ${{ steps.bump_version.outputs.next-version }}",
          overwrite: 'true'
